services:
  m6o4-solutions:
    image: ghcr.io/m6o4solutions/m6o4-solutions-web-project:latest
    container_name: m6o4-solutions
    restart: unless-stopped
    networks:
      - traefik-network
    env_file:
      - stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.m6o4-solutions.rule=Host(`m6o4solutions.com`) || Host(`www.m6o4solutions.com`)"
      - "traefik.http.routers.m6o4-solutions.entrypoints=websecure"
      - "traefik.http.routers.m6o4-solutions.tls.certresolver=letsencrypt"
      - "traefik.http.services.m6o4-solutions.loadbalancer.server.port=3000"

networks:
  traefik-network:
    external: true
    name: traefik-network
